# Generated by Django 2.2.7 on 2019-11-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_got'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Got',
        ),
        migrations.AddField(
            model_name='find',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
