# Generated by Django 2.2.7 on 2019-11-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0005_auto_20191122_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='words',
            field=models.CharField(max_length=50),
        ),
    ]
