# Generated by Django 2.2.7 on 2019-11-22 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0007_remove_search_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_search', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='simple.Search')),
                ('word_search', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='simple.Find')),
            ],
        ),
    ]
