# Generated by Django 2.2.7 on 2019-11-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0008_final'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='find',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='final',
            name='text_search',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='simple.Search'),
        ),
        migrations.AlterField(
            model_name='final',
            name='word_search',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='simple.Find'),
        ),
    ]
