# Generated by Django 2.2.7 on 2019-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0009_auto_20191122_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='find',
            options={},
        ),
        migrations.AddField(
            model_name='find',
            name='location',
            field=models.ManyToManyField(blank=True, to='simple.Search'),
        ),
        migrations.DeleteModel(
            name='Final',
        ),
    ]
